CREATE USER IF NOT EXISTS client1;
CREATE DATABASE IF NOT EXISTS CLIENT_DB;
USE DATABASE CLIENT_DB;
CREATE SCHEMA IF NOT EXISTS clientinfo;
USE SCHEMA CLIENT_DB.clientinfo;
CREATE OR REPLACE TABLE TRIPS
(
     NAME INTEGER
    ,MOBILE INTEGER
    ,ADDRESS INTEGER
    ,BIRTH_YEAR INTEGER
    ,GENDER INTEGER
);
CREATE ROLE IF NOT EXISTS SUADMIN;